### ISSUE TITLE
Fix the footer on FlauntZone page

### ISSUE THREAD

**Issue by VidhiBhatt01** [VidhiBhatt01/Project-Revamp#1] opened 2021-11-01 14:58 UTC
![Issue 1](https://user-images.githubusercontent.com/83345228/139692324-77c7b20e-573d-4af9-b137-1eab51a8f93b.png)

**Comment by MAZ12211** [comment] 2021-11-02 19:44
I would like to work on this.

**Comment by VidhiBhatt01** [comment] 2021-11-03 14:02
> I would like to work on this.

Sure, go on. Happy contributing :)

**Comment by irenejoeunpark** [comment] 2021-11-18 21:14
Hi @VidhiBhatt01 I want to work on this!

**Comment by VidhiBhatt01** [comment] 2021-11-19 06:44
> Hi @VidhiBhatt01 I want to work on this!

Assigned.

**Comment by irenejoeunpark** [comment] 2021-11-22 08:13
Hi, node app.js does not work on my end, is there any other way to run it?

**Comment by kavania2002** [comment] 2021-11-22 08:28
@irenejoeunpark can you please tell us more about the error?

**Comment by irenejoeunpark** [comment] 2021-11-23 20:12
> @irenejoeunpark can you please tell us more about the error?

       throw new Error("Courier Auth Token is required.");
              ^

Error: Courier Auth Token is required.
    at exports.CourierClient (/Users/irenepark/Projects/Project-Revamp/node_modules/@trycourier/courier/lib/index.js:16:15)
    at file:///Users/irenepark/Projects/Project-Revamp/app.js:5:17
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)

Above message is showing when I run it "node app.js"

**Comment by kavania2002** [comment] 2021-11-24 05:44
the Problem is with Authentication of Courier API, we have used Courier API which needs an API key. That key must be kept secret.
If you want to explore, visits this site https://www.courier.com/. You need to create a new API and then create a .env file in which you can store like
`courierAPI={API_KEY}`

**Comment by VidhiBhatt01** [comment] 2021-11-24 05:55
@irenejoeunpark There is no need to run these API/ node files honestly. You just need to fix the footer from css file and run the flauntzone.html file with live server to verify the changes.

**Comment by irenejoeunpark** [comment] 2021-11-25 21:13
@VidhiBhatt01 But when I open the html file, it does not have css applied at all.

**Comment by irenejoeunpark** [comment] 2021-11-25 21:14
@VidhiBhatt01 How to run flauntzone.html with the server on my side?

**Comment by VidhiBhatt01** [comment] 2021-11-29 17:37
@irenejoeunpark Extremely sorry for the delayed response. 

Here's what you can do:
1. Download the repo as a zip file and then extract it.
2. Open this folder in any IDE you are using.
3. There is a subfolder named Project Revamp wherein all HTML, CSS, and JS files are located. From that open flautzone.html. Run it/ open it with the live server. ( I assume you are using VS Code)
4.  I checked it from my side again and the CSS is visible. If you still find it different, let us know. We can quickly get on a 15 min zoom call or you can just add a screenshot of your error here in the comments.
5.  If CSS is visible to you, you need to then go on in the FlauntZone Folder. ie. main repo folder -> Project Revamp -> FlauntZone -> CSS -> style.css
6. Once you have reached the style.css file; section 12 is dedicated to the footer and this is where you need to fix the error and make changes.
7. To verify your changes, save them and then open flauntzone.html again with the live server.


Note: If you don't know what a live server is, it's an extension in VS Code. If you don't have it, you can just search it and download the extension from the extension section in VS Code. It barely takes 2 mins. Once it is installed, you can right-click anywhere in the HTML file you wanna run and then choose the 'open with live server' option from the menu.

I hope this helped you clear your query. Still, if you are stuck somewhere feel free to reach out. Happy Contributing!

**Comment by VidhiBhatt01** [comment] 2021-12-20 12:22
@irenejoeunpark what's the update? are you working on this??

**Comment by Abhay2342** [comment] 2022-06-15 06:13
Can you assign this to me?

**Comment by Abhay2342** [comment] 2022-06-15 07:04
Please check my PR.

**Comment by VidhiBhatt01** [comment] 2022-06-15 13:35
Fixed via #5

**Closed as completed** 2022-06-15 13:35 UTC
Labels: bug, help wanted, good first issue, urgent
